# -*- coding: utf-8 -*-
"""final project visdat

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14VswJNcE3W6RWYfA-15FO8EfH8Q8N4VD
"""

#Rifqy Muhammad Alfian_1301200062
import pandas as pd
from bokeh.io import curdoc
from bokeh.plotting import figure
from bokeh.models import HoverTool, ColumnDataSource
from bokeh.models import CategoricalColorMapper
from bokeh.palettes import Spectral6
from bokeh.layouts import widgetbox, row, gridplot
from bokeh.models import Slider, Select

data = pd.read_csv('dataPadi.csv')
data.set_index('Tahun', inplace=True)
data

prov_list = data.Provinsi.unique().tolist()

# Make a color mapper: color_mapper
color_mapper = CategoricalColorMapper(factors=prov_list, palette=Spectral6)

data.rename(columns={'Suhu rata-rata':'suhu_rata','Curah hujan':'curah_hujan','Luas Panen':'luas_panen'}, inplace=True)
data

# Make the ColumnDataSource: source
source = ColumnDataSource(data={
    'x'       : data.loc[1993].Produksi,
    'y'       : data.loc[1993].luas_panen,
    'provinsi'  : data.loc[1993].Provinsi,
})

# Create the figure: plot
plot = figure(title='1993', x_axis_label='Jumlah Produksi', y_axis_label='Luas Panen',
           plot_height=400, plot_width=700, tools=[HoverTool(tooltips='@provinsi')])

plot.circle(x='x', y='y', source=source, fill_alpha=0.8,
           color=dict(field='provinsi', transform=color_mapper), legend='provinsi')

# Set the legend and axis attributes
plot.legend.location = 'top_right'

# Define the callback function: update_plot
def update_plot(attr, old, new):
    # set the `yr` name to `slider.value` and `source.data = new_data`
    yr = slider.value
    x = x_select.value
    y = y_select.value
    # Label axes of plot
    plot.xaxis.axis_label = x
    plot.yaxis.axis_label = y
    # new data
    new_data = {
    'x'       : data.loc[yr][x],
    'y'       : data.loc[yr][y],
    'provinsi'  : data.loc[yr].Provinsi,
    }
    source.data = new_data
    # Add title to figure: plot.title.text
    plot.title.text = 'Gapminder data for %d' % yr

# Make a slider object: slider
slider = Slider(start=1993, end=2020, step=1, value=1993, title='Year')
slider.on_change('value',update_plot)

# Make dropdown menu for x and y axis
# Create a dropdown Select widget for the x data: x_select
x_select = Select(
    options=['Produksi', 'luas_panen', 'curah_hujan', 'Kelembapan', 'suhu_rata'],
    value='Produksi',
    title='x-axis data'
)
# Attach the update_plot callback to the 'value' property of x_select
x_select.on_change('value', update_plot)

# Create a dropdown Select widget for the y data: y_select
y_select = Select(
    options=['Produksi', 'luas_panen', 'curah_hujan', 'Kelembapan', 'suhu_rata'],
    value='luas_panen',
    title='y-axis data'
)
# Attach the update_plot callback to the 'value' property of y_select
y_select.on_change('value', update_plot)

# Create layout and add to current document
layout = row(widgetbox(slider, x_select, y_select), plot)
curdoc().add_root(layout)